In [1]:
import pandas as pd

# Clean data

In [7]:
grad_pct = pd.read_csv('../data/processed/grad_pct_per_ENTITY.csv')
perc_ecdis = pd.read_csv('../data/processed/PER_ECDIS_per_ENTITY.csv')

In [17]:
grad_pct

,SUBGROUP_NAME,REPORT_SCHOOL_YEAR,lea_beds,GRAD_PCT
0,All Students,2024-25,241001060000,95%
1,Parent Not in Armed Forces,2024-25,241001060000,95%
2,Not Economically Disadvantaged,2024-25,241001060000,97%
3,Economically Disadvantaged,2024-25,241001060000,94%
4,Not English Language Learner,2024-25,241001060000,95%
...,...,...,...,...
142045,White,2024-25,261600010000,-
142046,Hispanic,2024-25,261600010000,44%
142047,Black,2024-25,261600010000,46%
142048,Students with Disabilities,2024-25,261600010000,40%
142049,General Education Students,2024-25,261600010000,41%

In [24]:
grad_pct[['SUBGROUP_NAME', 'lea_beds']].drop_duplicates()

                         SUBGROUP_NAME      lea_beds
0                         All Students  241001060000
1           Parent Not in Armed Forces  241001060000
2       Not Economically Disadvantaged  241001060000
3           Economically Disadvantaged  241001060000
4         Not English Language Learner  241001060000
...                                ...           ...
141546                        Hispanic  140600861185
141547          Asian/Pacific Islander  140600861185
141548                           Black  140600861185
141549      Students with Disabilities  140600861185
141550      General Education Students  140600861185

[15316 rows x 2 columns]

In [21]:
perc_ecdis

          ENTITY_CD    YEAR  PER_ECDIS
0                 1  2023.0       75.0
1                 2  2023.0       84.0
2                 3  2023.0       74.0
3                 4  2023.0       60.0
4                 5  2023.0       44.0
...             ...     ...        ...
16538  680601060002  2025.0       54.0
16539  680601060005  2025.0       63.0
16540  680801040000  2025.0       61.0
16541  680801040001  2025.0       57.0
16542  680801040002  2025.0       65.0

[16543 rows x 3 columns]